[packages.core]
versioned_files = ["packages/core/package.json"]
changelog = "packages/core/CHANGELOG.md"

[packages.logger]
versioned_files = ["packages/logger/package.json"]
changelog = "packages/logger/CHANGELOG.md"

[packages.web]
versioned_files = ["apps/web/package.json"]
changelog = "apps/web/CHANGELOG.md"

[packages.mobile]
versioned_files = ["apps/mobile/package.json"]
changelog = "apps/mobile/CHANGELOG.md"

[packages.desktop]
versioned_files = ["apps/desktop/package.json"]
changelog = "apps/desktop/CHANGELOG.md"

[packages.cli]
versioned_files = ["apps/cli/package.json"]
changelog = "apps/cli/CHANGELOG.md"

[github]
owner = "SiaFoundation"
repo = "sia-storage-app"

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "Command"
command = "git switch -c release"

[[workflows.steps]]
type = "PrepareRelease"
ignore_conventional_commits = true

[[workflows.steps]]
type = "Command"
command = "bun apps/mobile/scripts/syncAppVersion.ts"

[[workflows.steps]]
type = "Command"
command = "bun install"

[[workflows.steps]]
type = "Command"
command = "bunx oxfmt --write ."

[[workflows.steps]]
type = "Command"
command = "git add -A"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: release\""

[[workflows.steps]]
type = "Command"
command = "git push --force --set-upstream origin release"

[[workflows.steps]]
type = "Command"
command = "bun scripts/create-release-pr.ts"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"
