export {
  type Directory,
  type DirectoryWithCount,
  deleteDirectory,
  deleteDirectoryAndTrashFiles,
  getOrCreateDirectory,
  insertDirectory,
  moveFilesToDirectory,
  moveFileToDirectory,
  queryAllDirectoriesWithCounts,
  queryCountFilesWithDirectories,
  queryDirectoryNameForFile,
  renameDirectory,
  sanitizeDirectoryName,
  syncDirectoryFromMetadata,
} from './directories'
export {
  createFileRecordWithLocalObject,
  deleteAllFileRecords,
  deleteFileRecordAndThumbnails,
  deleteFileRecordById,
  deleteFileRecordsAndThumbnails,
  deleteFileRecordsByThumbForId,
  deleteLostFiles,
  deleteManyFileRecordsByIds,
  type FileRecordsQueryOpts,
  insertFileRecord,
  insertManyFileRecords,
  queryFileRecordByContentHash,
  queryFileRecordById,
  queryFileRecordByObjectId,
  queryFileRecords,
  queryFileRecordsByContentHashes,
  queryFileRecordsByLocalIds,
  queryFileRecordsCount,
  queryFileRecordsStats,
  queryLocalFileCount,
  queryLocalFileStats,
  queryLocalOnlyFiles,
  queryLostFileCount,
  queryLostFileStats,
  readFileRecord,
  readFileRecordByContentHash,
  readFileRecordByObjectId,
  readFileRecordsByContentHashes,
  readFileRecordsByIds,
  readFileRecordsByLocalIds,
  transformRow,
  updateFileDirectory,
  updateFileRecordFields,
  updateFileRecordWithLocalObject,
  updateManyFileRecordFields,
} from './files'
export {
  calcFsFilesMetadataTotalSize,
  deleteFsFileMetadata,
  deleteFsFileMetadataBatch,
  type FsMetaRow,
  readFsFileMetadata,
  updateFsFileMetadataUsedAt,
  upsertFsFileMetadata,
} from './fs'
export {
  countLocalObjectsForFile,
  deleteLocalObjectById,
  deleteLocalObjectsByFileId,
  deleteManyLocalObjectsByFileIds,
  insertLocalObject,
  queryLocalObjectsForFile,
  queryLocalObjectsForFiles,
} from './localObjects'
export {
  addTagToFile,
  addTagToFiles,
  deleteTag,
  ensureSystemTags,
  getOrCreateTag,
  insertFileTag,
  insertTag,
  queryAllTagsWithCounts,
  queryIsFavorite,
  queryTagNamesForFile,
  queryTagsByPrefix,
  queryTagsForFile,
  removeTagFromFile,
  removeTagFromFiles,
  renameTag,
  SYSTEM_TAGS,
  syncTagsFromMetadata,
  type Tag,
  type TagWithCount,
  toggleFavorite,
} from './tags'
export {
  queryBestThumbnailByFileId,
  queryThumbnailExistsForFileIdAndSize,
  queryThumbnailFileInfoByFileIds,
  queryThumbnailRecordByFileIdAndSize,
  queryThumbnailSizesForFileId,
  queryThumbnailsByFileId,
} from './thumbnails'
export {
  autoPurgeOldTrashedFiles,
  autoPurgeOldTrashedFilesWithCleanup,
  type FileCleanupDeps,
  permanentlyDeleteFiles,
  permanentlyDeleteFilesWithCleanup,
  restoreFiles,
  trashFiles,
} from './trash'
