export {
  type Directory,
  type DirectoryWithCount,
  deleteDirectory,
  deleteDirectoryAndTrashFiles,
  directoryBreadcrumbs,
  directoryDisplayName,
  directoryParentPath,
  escapeLikePattern,
  getOrCreateDirectory,
  getOrCreateDirectoryAtPath,
  insertDirectory,
  moveDirectory,
  moveFilesToDirectory,
  moveFileToDirectory,
  queryAllDirectoriesWithCounts,
  queryCountFilesWithDirectories,
  queryDirectoryById,
  queryDirectoryByPath,
  queryDirectoryChildren,
  queryDirectoryPathForFile,
  queryFileByNameInDirectory,
  queryFilesByDirectoryPath,
  renameDirectory,
  sanitizeDirectoryPath,
  sanitizeDirectorySegment,
  syncDirectoryFromMetadata,
  syncManyDirectoriesFromMetadata,
} from './directories'
export {
  queryUploadStats,
  type UploadCategoryStats,
  type UploadStats,
} from './fileStats'
export {
  createFileRecordWithLocalObject,
  deleteAllFileRecords,
  deleteFileRecordAndThumbnails,
  deleteFileRecordById,
  deleteFileRecordsAndThumbnails,
  deleteFileRecordsByThumbForId,
  deleteLostFiles,
  deleteManyFileRecordsByIds,
  type FileRecordsQueryOpts,
  insertFileRecord,
  insertManyFileRecords,
  moveAllFileVersions,
  queryActiveFileSummaries,
  queryFileRecordByContentHash,
  queryFileRecordById,
  queryFileRecordByName,
  queryFileRecordByObjectId,
  queryFileRecordRowsByIds,
  queryFileRecordRowsByObjectIds,
  queryFileRecords,
  queryFileRecordsByContentHashes,
  queryFileRecordsByLocalIds,
  queryFileRecordsCount,
  queryFileRecordsStats,
  queryFileVersions,
  queryLocalFileCount,
  queryLocalFileStats,
  queryLocalOnlyFiles,
  queryLostFileCount,
  queryLostFileStats,
  queryUnuploadedFileCount,
  queryUnuploadedFiles,
  queryUploadedFileIds,
  readFileRecord,
  readFileRecordByContentHash,
  readFileRecordByName,
  readFileRecordByObjectId,
  readFileRecordsByContentHashes,
  readFileRecordsByIds,
  readFileRecordsByLocalIds,
  recalculateCurrentForFileIds,
  recalculateCurrentForGroup,
  recalculateCurrentForGroups,
  renameAllFileVersions,
  tombstoneFileRecords,
  transformRow,
  trashAllFileVersions,
  updateFileDirectory,
  updateFileRecordFields,
  updateFileRecordWithLocalObject,
  updateManyFileRecordFields,
  upsertManyFileRecords,
} from './files'
export {
  calcFsFilesMetadataTotalSize,
  deleteFsFileMetadata,
  deleteFsFileMetadataBatch,
  type FsMetaRow,
  queryFsCacheEvictionCandidates,
  queryOrphanedFileIds,
  readFsFileMetadata,
  updateFsFileMetadataUsedAt,
  upsertFsFileMetadata,
} from './fs'
export {
  ALL_CATEGORIES,
  buildLatestVersionFilter,
  buildLibraryQueryParts,
  type Category,
  type LibraryQueryParams,
  queryDirectoryFileCount,
  queryFileCountWithFilters,
  queryFileExists,
  queryFilePositionInSortedList,
  queryLibraryFileCount,
  queryLibraryFiles,
  queryMediaFileCount,
  querySortedFileIds,
  queryTagFileCount,
  queryUnfiledFileCount,
  type SortBy,
  type SortDir,
  UNFILED_DIRECTORY_ID,
} from './library'
export {
  countLocalObjectsForFile,
  deleteLocalObjectById,
  deleteLocalObjectsByFileId,
  deleteManyLocalObjectsByFileIds,
  deleteManyLocalObjectsByObjectIds,
  insertLocalObject,
  insertManyLocalObjects,
  queryFilesWithNoObjects,
  queryLocalObjectsForFile,
  queryLocalObjectsForFiles,
} from './localObjects'
export {
  deleteAllLogs,
  insertLog,
  insertManyLogs,
  type LogRow,
  queryAvailableLogScopes,
  queryLogCount,
  queryLogs,
  rotateLogs,
} from './logs'
export {
  addTagToFile,
  addTagToFiles,
  deleteTag,
  ensureSystemTags,
  getOrCreateTag,
  insertFileTag,
  insertTag,
  queryAllTagsWithCounts,
  queryIsFavorite,
  queryTagNamesForFile,
  queryTagsByPrefix,
  queryTagsForFile,
  removeTagFromFile,
  removeTagFromFiles,
  renameTag,
  SYSTEM_TAGS,
  syncManyTagsFromMetadata,
  syncTagsFromMetadata,
  type Tag,
  type TagWithCount,
  toggleFavorite,
} from './tags'
export {
  queryBestThumbnailByFileId,
  queryThumbnailCandidatePage,
  queryThumbnailExistsForFileIdAndSize,
  queryThumbnailFileInfoByFileIds,
  queryThumbnailRecordByFileIdAndSize,
  queryThumbnailScanProgress,
  queryThumbnailSizesForFileId,
  queryThumbnailsByFileId,
  type ThumbnailCandidateRow,
} from './thumbnails'
export {
  autoPurgeOldTrashedFiles,
  permanentlyDeleteFiles,
  restoreFiles,
  trashFiles,
} from './trash'
