#!/usr/bin/env bun
import * as fs from 'fs'
import * as path from 'path'
import { $ } from 'bun'

const CLI_DIR = path.resolve(import.meta.dirname, '..')
const UI_DIR = path.join(CLI_DIR, 'ui')
const OUT_DIR = path.join(CLI_DIR, 'dist', 'ui')
const BUNDLE_FILE = path.join(CLI_DIR, 'src', 'serve', 'ui-bundle.ts')

async function build() {
  console.log('Processing Tailwind CSS...')
  const tailwindOut = path.join(UI_DIR, 'dist-styles.css')
  await $`bunx @tailwindcss/cli -i ${path.join(UI_DIR, 'styles.css')} -o ${tailwindOut} --minify`.cwd(
    CLI_DIR,
  )

  // Bun.build inlines whatever styles.css references, so we swap the source
  // for the Tailwind-processed copy across the build and restore it after.
  const origStyles = fs.readFileSync(path.join(UI_DIR, 'styles.css'), 'utf-8')
  fs.copyFileSync(tailwindOut, path.join(UI_DIR, 'styles.css'))

  console.log('Building UI...')
  try {
    const result = await Bun.build({
      entrypoints: [path.join(UI_DIR, 'index.html')],
      outdir: OUT_DIR,
      minify: true,
    })

    if (!result.success) {
      console.error('Build failed:')
      for (const log of result.logs) {
        console.error(log)
      }
      process.exit(1)
    }

    console.log(`Built ${result.outputs.length} files`)
  } finally {
    fs.writeFileSync(path.join(UI_DIR, 'styles.css'), origStyles)
    fs.rmSync(tailwindOut, { force: true })
  }

  const files = fs.readdirSync(OUT_DIR)
  const htmlFile = files.find((f) => f === 'index.html')
  const jsFile = files.find((f) => f.endsWith('.js'))
  const cssFile = files.find((f) => f.endsWith('.css'))

  if (!htmlFile || !jsFile) {
    console.error('Missing output files:', { htmlFile, jsFile, cssFile })
    process.exit(1)
  }

  let html = fs.readFileSync(path.join(OUT_DIR, htmlFile), 'utf-8')
  const js = fs.readFileSync(path.join(OUT_DIR, jsFile), 'utf-8')
  const css = cssFile ? fs.readFileSync(path.join(OUT_DIR, cssFile), 'utf-8') : ''

  // Generate content hash for cache busting
  const { createHash } = await import('node:crypto')
  const hash = createHash('md5').update(js).update(css).digest('hex').slice(0, 8)

  // Rewrite the HTML to use hashed absolute paths
  html = html.replace(
    new RegExp(`\\./${jsFile.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`, 'g'),
    `/_ui/bundle.${hash}.js`,
  )
  if (cssFile) {
    html = html.replace(
      new RegExp(`\\./${cssFile.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`, 'g'),
      `/_ui/bundle.${hash}.css`,
    )
  }

  // Generate the TypeScript bundle file
  const bundleTs = `// AUTO-GENERATED by scripts/build-ui.ts — do not edit
export const UI_HASH = ${JSON.stringify(hash)}
export const UI_HTML = ${JSON.stringify(html)}
export const UI_JS = ${JSON.stringify(js)}
export const UI_CSS = ${JSON.stringify(css)}
`

  fs.writeFileSync(BUNDLE_FILE, bundleTs)
  console.log(`Generated ${BUNDLE_FILE}`)
  console.log(`  HTML: ${html.length} bytes`)
  console.log(`  JS: ${js.length} bytes`)
  console.log(`  CSS: ${css.length} bytes`)
}

build()
