/**
 * Native test runner for the import-sources module.
 *
 * bun scripts/nativeTest.ts ios Swift host suite (headless macOS)
 * bun scripts/nativeTest.ts ios --simulator Photos/picker XCTest on a simulator of its own
 * bun scripts/nativeTest.ts android Robolectric suite (headless JVM;
 * needs android/ from a prior prebuild)
 */
import { Database } from 'bun:sqlite'
import { existsSync, readdirSync } from 'node:fs'
import { homedir } from 'node:os'
import path from 'node:path'

const appRoot = path.resolve(import.meta.dir, '..')
const platform = process.argv[2]
const simulator = process.argv.includes('--simulator')

function run(cmd: string[], cwd: string): number {
  console.log(`$ ${cmd.join(' ')}`)
  const proc = Bun.spawnSync(cmd, { cwd, stdout: 'inherit', stderr: 'inherit' })
  return proc.exitCode ?? 1
}

function output(cmd: string[]): string {
  return new TextDecoder().decode(Bun.spawnSync(cmd).stdout).trim()
}

/**
 * Rewrites the app host's Photos grant into the form tapping Allow on the
 * prompt leaves in the simulator's TCC database: auth_reason 2 (the user's
 * consent) and auth_version 2. `simctl privacy grant photos` writes reason 4
 * and version 1, which Photos on Xcode 26.2's simulators reads as not
 * determined, so every test waited for access until it timed out. Returns
 * whether the entry was found.
 */
function grantPhotosAsUser(udid: string, bundleId: string): boolean {
  const tcc = path.join(
    homedir(),
    'Library/Developer/CoreSimulator/Devices',
    udid,
    'data/Library/TCC/TCC.db',
  )
  const db = new Database(tcc)
  try {
    const result = db
      .query(
        `UPDATE access SET auth_value = 2, auth_reason = 2, auth_version = 2
         WHERE service = 'kTCCServicePhotos' AND client = ?`,
      )
      .run(bundleId)
    return result.changes > 0
  } finally {
    db.close()
  }
}

/** The generated workspace, whose name follows the build variant. */
function findWorkspace(iosDir: string): string | null {
  return readdirSync(iosDir).find((f) => f.endsWith('.xcworkspace')) ?? null
}

const SIMULATOR_NAME = 'sia-native-tests'

/**
 * The simulator these tests run on, created on the newest iOS runtime the
 * first time and booted when it is not. The tests seed and read its photo
 * library, so it is one of their own: sim's phones and anyone's own simulator
 * can be booted beside it. Returns its UDID and whether this run booted it.
 */
function testSimulator(): { udid: string; booted: boolean } | null {
  const devices = JSON.parse(output(['xcrun', 'simctl', 'list', 'devices', 'available', '--json']))
    .devices as Record<string, Array<{ name: string; udid: string; state: string }>>
  let device = Object.values(devices)
    .flat()
    .find((d) => d.name === SIMULATOR_NAME)
  if (!device) {
    const runtimes = (
      JSON.parse(output(['xcrun', 'simctl', 'list', 'runtimes', 'available', '--json']))
        .runtimes as Array<{
        identifier: string
        platform?: string
        supportedDeviceTypes: Array<{ identifier: string; productFamily?: string }>
      }>
    ).filter((r) => r.platform === 'iOS')
    const runtime = runtimes.at(-1)
    const deviceType = runtime?.supportedDeviceTypes.find((t) => t.productFamily === 'iPhone')
    if (!runtime || !deviceType) return null
    const udid = output([
      'xcrun',
      'simctl',
      'create',
      SIMULATOR_NAME,
      deviceType.identifier,
      runtime.identifier,
    ])
    if (!udid) return null
    device = { name: SIMULATOR_NAME, udid, state: 'Shutdown' }
  }
  if (device.state === 'Booted') return { udid: device.udid, booted: false }
  if (run(['xcrun', 'simctl', 'boot', device.udid], appRoot) !== 0) return null
  if (run(['xcrun', 'simctl', 'bootstatus', device.udid, '-b'], appRoot) !== 0) return null
  return { udid: device.udid, booted: true }
}

if (platform === 'ios') {
  if (!simulator) {
    process.exit(run(['swift', 'test', '--package-path', 'modules/import-sources/ios'], appRoot))
  }
  // Simulator tier. The podspec's testspec is inert for a plain `pod install`,
  // so opt the generated Podfile into it before installing. Editing that Podfile
  // is safe and needs no cleanup: ios/ is gitignored and regenerated by prebuild.
  const iosDir = path.join(appRoot, 'ios')
  const podfile = path.join(iosDir, 'Podfile')
  if (!existsSync(podfile)) {
    console.error('ios/ not generated; run `bunx expo prebuild -p ios` first.')
    process.exit(1)
  }
  const scheme = 'ImportSources-Unit-Tests'
  const sim = testSimulator()
  if (!sim) {
    console.error(`could not create or boot the ${SIMULATOR_NAME} simulator.`)
    process.exit(1)
  }
  const udid = sim.udid
  // Shut down only a simulator this run booted, so one left running on
  // purpose stays up. An exit handler covers every failure path below,
  // including a throw.
  if (sim.booted) {
    process.on('exit', () => {
      Bun.spawnSync(['xcrun', 'simctl', 'shutdown', udid])
    })
  }
  const testspec =
    "pod 'ImportSources', :path => '../modules/import-sources/ios', :testspecs => ['Tests']"
  const original = await Bun.file(podfile).text()
  if (!original.includes(testspec)) {
    const patched = original.replace(/use_expo_modules!/, `use_expo_modules!\n  ${testspec}`)
    if (patched === original) {
      console.error('no `use_expo_modules!` line in the Podfile to attach the testspec to.')
      process.exit(1)
    }
    await Bun.write(podfile, patched)
  }
  const appHostBundleId = `org.cocoapods.AppHost-${scheme}`
  // An alert already on screen belongs to SpringBoard, not the process that
  // raised it, so killing a previous run leaves its permission prompt up and
  // the next run blocks behind it. Terminate and reset before building.
  run(['xcrun', 'simctl', 'terminate', udid, appHostBundleId], appRoot)
  run(['xcrun', 'simctl', 'privacy', udid, 'reset', 'all', appHostBundleId], appRoot)
  if (run(['pod', 'install'], iosDir) !== 0) process.exit(1)
  // TCC terminates a process that touches Photos with no usage string, and the
  // app host CocoaPods generates has none. A testspec's `info_plist` configures
  // the test bundle, not the host, so the host's plist is patched after install.
  const hostPlist = path.join(iosDir, 'Pods', `AppHost-${scheme}`, `AppHost-${scheme}-Info.plist`)
  if (!existsSync(hostPlist)) {
    console.error(`generated app host plist missing at ${hostPlist}`)
    process.exit(1)
  }
  for (const [key, value] of [
    ['NSPhotoLibraryUsageDescription', 'Reads the assets these tests seed.'],
    ['NSPhotoLibraryAddUsageDescription', 'Seeds the assets these tests read back.'],
  ]) {
    if (run(['plutil', '-replace', key, '-string', value, hostPlist], iosDir) !== 0) {
      process.exit(1)
    }
  }
  const workspace = findWorkspace(iosDir)
  if (!workspace) {
    console.error('no .xcworkspace in ios/; `pod install` did not complete.')
    process.exit(1)
  }
  // Build, install, grant, then test - in that order and as separate steps.
  // A plain `xcodebuild test` installs the app host itself at test time, which
  // resets its TCC entries and discards any grant made beforehand; the tests
  // then block on a photo-access prompt nothing can answer.
  const destination = `platform=iOS Simulator,id=${udid}`
  const xcargs = ['-workspace', workspace, '-scheme', scheme, '-destination', destination]
  if (run(['xcodebuild', 'build-for-testing', ...xcargs], iosDir) !== 0) process.exit(1)

  const built = output([
    'xcodebuild',
    '-showBuildSettings',
    '-workspace',
    path.join(iosDir, workspace),
    '-scheme',
    scheme,
    '-destination',
    destination,
    '-json',
  ])
  const settings = JSON.parse(built) as Array<{ buildSettings: Record<string, string> }>
  // TARGET_BUILD_DIR resolves to the test bundle's own directory
  // (<products>/AppHost-X.app/PlugIns); the host bundle sits at the products
  // root, so trim that suffix rather than joining onto it.
  const targetDir = settings[0]?.buildSettings?.TARGET_BUILD_DIR ?? ''
  const productsRoot = targetDir.replace(/\/[^/]+\.app(\/PlugIns)?$/, '')
  const appHost = path.join(productsRoot, `AppHost-${scheme}.app`)
  if (!productsRoot || !existsSync(appHost)) {
    console.error(`built app host not found at ${appHost}`)
    process.exit(1)
  }
  if (run(['xcrun', 'simctl', 'install', udid, appHost], iosDir) !== 0) process.exit(1)
  // `photos` and `photos-add` are independent TCC services: read access does not
  // imply write, and the tests seed assets before reading them back. Both grants
  // must follow the install, since installing resets the app's TCC entries.
  for (const service of ['photos', 'photos-add']) {
    if (
      run(['xcrun', 'simctl', 'privacy', udid, 'grant', service, appHostBundleId], iosDir) !== 0
    ) {
      process.exit(1)
    }
  }
  if (!grantPhotosAsUser(udid, appHostBundleId)) {
    console.error('simctl granted Photos access but left no TCC entry to rewrite.')
    process.exit(1)
  }
  // On a failure xcodebuild collects a sysdiagnose from the simulator by
  // default, and on a CI runner that waits out a 600 second timeout.
  const result = run(
    ['xcodebuild', 'test-without-building', ...xcargs, '-collect-test-diagnostics', 'never'],
    iosDir,
  )
  process.exit(result)
}

if (platform === 'android') {
  const androidDir = path.join(appRoot, 'android')
  if (!existsSync(path.join(androidDir, 'gradlew'))) {
    console.error('android/ not generated; run `bunx expo prebuild -p android` first.')
    process.exit(1)
  }
  process.exit(run(['./gradlew', ':import-sources:testDebugUnitTest'], androidDir))
}

console.error('usage: bun scripts/nativeTest.ts <ios|android> [--simulator]')
process.exit(1)
