name: PR

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:

# cancel previous runs when the PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          bun_version: 1.2.19
      - run: bun run lint

  typecheck:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          bun_version: 1.2.19
      - run: bun run typecheck

  test-core:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          bun_version: 1.2.19
      - run: bun --cwd packages/core test

  test-mobile:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          bun_version: 1.2.19
      - run: bun --cwd apps/mobile test

  test-integration:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          bun_version: 1.2.19
      - run: bun --cwd apps/integration test
